### ISSUE TITLE
Old game data with WAL causes problems

### ISSUE THREAD

**Issue by synth-ruiner** [seleb/bitsy-merge#9]
probably not a pressing issue, but the old way of defining walls in a room ("WAL a,b,c") will be converted to "PAL a,b,c" after merge, and other data like exits will be lost in the process.
![Screenshot from 2020-07-02 18-29-20](https://user-images.githubusercontent.com/8642013/86393521-19f72e00-bc95-11ea-9127-271a293725d4.png)

**Comment by seleb** [comment]
issue with parser, going to address in Ragzouken/npm-bitsy-parser#2
